export const REQUEST_SEARCH_API_DATA = 'REQUEST_SEARCH_API_DATA';
export const RECEIVE_SEARCH_API_DATA = 'RECEIVE_SEARCH_API_DATA';
export const REQUEST_USER_REPOS = 'REQUEST_USER_REPOS';
export const RECEIVE_USER_REPOS = 'RECEIVE_USER_REPOS';
export const REQUEST_USER_DATA = 'REQUEST_USER_DATA';
export const RECEIVE_USER_DATA = 'RECEIVE_USER_DATA';
